# Generated by Django 4.2.5 on 2025-03-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YogaPoseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pose_name', models.CharField(max_length=100, unique=True)),
                ('english_name', models.CharField(max_length=100)),
                ('benefits', models.TextField()),
                ('level', models.CharField(max_length=20)),
                ('hold_duration', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='YogaPoseHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pose_name', models.CharField(max_length=100, unique=True)),
                ('english_name', models.CharField(max_length=100)),
                ('hold_duration', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='YogaPoseIdealAngle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pose_name', models.CharField(db_index=True, max_length=100)),
                ('view', models.CharField(db_index=True, max_length=100)),
                ('is_flipped', models.BooleanField(default=False)),
                ('left_elbow_angle_mean', models.FloatField()),
                ('left_elbow_angle_std', models.FloatField()),
                ('left_shoulder_angle_mean', models.FloatField()),
                ('left_shoulder_angle_std', models.FloatField()),
                ('left_knee_angle_mean', models.FloatField()),
                ('left_knee_angle_std', models.FloatField()),
                ('left_hip_angle_mean', models.FloatField()),
                ('left_hip_angle_std', models.FloatField()),
                ('left_ankle_angle_mean', models.FloatField()),
                ('left_ankle_angle_std', models.FloatField()),
                ('right_elbow_angle_mean', models.FloatField()),
                ('right_elbow_angle_std', models.FloatField()),
                ('right_shoulder_angle_mean', models.FloatField()),
                ('right_shoulder_angle_std', models.FloatField()),
                ('right_knee_angle_mean', models.FloatField()),
                ('right_knee_angle_std', models.FloatField()),
                ('right_hip_angle_mean', models.FloatField()),
                ('right_hip_angle_std', models.FloatField()),
                ('right_ankle_angle_mean', models.FloatField()),
                ('right_ankle_angle_std', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['pose_name', 'view', 'is_flipped'], name='pose_select_pose_na_1b88ee_idx')],
                'unique_together': {('pose_name', 'view', 'is_flipped')},
            },
        ),
    ]
