# Generated by Django 4.2.5 on 2025-04-04 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pose_selection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('UPLOAD', 'Photo Upload'), ('REALTIME', 'Real-time Practice')], default='UPLOAD', max_length=10)),
                ('last_practice_date', models.DateField()),
                ('practice_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pose_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pose_history', to='pose_selection.yogaposeidealangle')),
                ('user_mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
