# Generated by Django 4.2.5 on 2025-03-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pose_selection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YogaPoseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pose_name', models.CharField(max_length=100, unique=True)),
                ('english_name', models.CharField(max_length=100)),
                ('benefits', models.TextField()),
                ('level', models.CharField(max_length=20)),
                ('hold_duration', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='YogaPoseHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pose_name', models.CharField(max_length=100, unique=True)),
                ('english_name', models.CharField(max_length=100)),
                ('hold_duration', models.CharField(max_length=20)),
            ],
        ),
    ]
