# Generated by Django 4.2.5 on 2025-04-04 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pose_selection', '0002_userhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserHistory',
        ),
    ]
