# Generated by Django 4.2.5 on 2025-04-08 09:56

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pose_selection', '0003_delete_userhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='YogaPoseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pose_name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='D:\\YogaPC\\ypc\\media\\pose_images'), upload_to='pose_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='yogaposedetails',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pose_details', to='pose_selection.yogaposeimage'),
        ),
        migrations.AddField(
            model_name='yogaposehold',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pose_hold', to='pose_selection.yogaposeimage'),
        ),
    ]
