# Generated by Django 4.2.5 on 2025-04-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pose_selection', '0004_yogaposeimage_yogaposedetails_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yogaposeimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
