# Generated by Django 4.2.5 on 2025-04-08 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pose_selection', '0005_alter_yogaposeimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yogaposedetails',
            name='image',
        ),
        migrations.RemoveField(
            model_name='yogaposehold',
            name='image',
        ),
        migrations.DeleteModel(
            name='YogaPoseImage',
        ),
    ]
