# Generated by Django 4.2.5 on 2025-04-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pose_selection', '0006_remove_yogaposedetails_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogaposedetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
